spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/musicDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: "${MYSQL_PASSWORD}"
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    #    For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
